### ISSUE TITLE
Cannot declare class WC_Gateway_MPESA

### ISSUE THREAD

**Issue by eugenemrobert** [pesakite/mpesa-stk-wc#1]
PHP Fatal error:  Cannot declare class WC_Gateway_MPESA, because the name is already in use in /home/xxx/public_html/wp-content/plugins/mpesa-stk-wc-master/mpesa-stk-wc.php on line 177

**Comment by mwamodo** [comment]
Do you have another plugin installed? There is only one instance of that class.
Also what file is causing that error?

**Comment by eugenemrobert** [comment]
> Do you have another plugin installed? There is only one instance of that class.
> Also what file is causing that error?

>Installed plugins- Elementor and Oceanwp plugins(Ocean Extra, Ocean Product Sharing, Ocean Modal Window)
>I don't know which file is causing the error

**Comment by mwamodo** [comment]
Do you have Wordpress Woocommerce Installed?

**Comment by eugenemrobert** [comment]
> Do you have Wordpress Woocommerce Installed?

yes

**Comment by mwamodo** [comment]
I have installed this on several versions of WordPress but could not reproduce that error. What have you done to get the error?

**Comment by eugenemrobert** [comment]
I just uploaded the plugin and encountered the error on clicking the activate button. I will consider re-installing WordPress and starting over again
