### ISSUE TITLE
Operator does not exist

### ISSUE THREAD

**Issue by maxwellmandela** [pesakite/mpesa-stk-wc#2]
![mpesa operator error](https://user-images.githubusercontent.com/5698497/98098970-0e647f80-1ea0-11eb-96ce-ca45a16d738e.png)

Hi @mwamodo could you assist with this, 

I was wondering if its because of SSL problem. 
Thanks

**Comment by mwamodo** [comment]
I am not totally sure about that. But it looks like an error from woocommerce.

**Comment by mwamodo** [comment]
![Screenshot from 2020-11-05 10-40-30](https://user-images.githubusercontent.com/52991058/98212374-8b513100-1f54-11eb-9264-84ea3c1d348d.png)
Its something close to that and that is just woocommerce without plugins.
